# Generated by Django 5.1.1 on 2024-11-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
