# Generated by Django 5.1.1 on 2024-09-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='job_designation',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='job',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='training',
        ),
        migrations.RemoveField(
            model_name='educationinfo',
            name='name_of_exam',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='driving_license_passport',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='e_tin',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='religion',
        ),
        migrations.DeleteModel(
            name='AddressInfo',
        ),
        migrations.DeleteModel(
            name='ExperienceInfo',
        ),
        migrations.DeleteModel(
            name='JobInfo',
        ),
        migrations.DeleteModel(
            name='TrainingInfo',
        ),
    ]
