# Generated by Django 5.1.1 on 2025-01-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
