# Generated by Django 5.1.1 on 2024-11-03 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_balance_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
