# Generated by Django 5.1.1 on 2024-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_balance_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='transaction_date',
            new_name='last_transaction_date',
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.IntegerField(default=-599000),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
