# Generated by Django 5.1.1 on 2024-11-04 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_personalinfo_last_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('amount_spent', models.IntegerField()),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='student.balance')),
            ],
        ),
    ]
