# Generated by Django 5.1.1 on 2024-11-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_expense_balance_alter_expense_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=150),
        ),
        migrations.AddField(
            model_name='expense',
            name='types',
            field=models.CharField(blank=True, choices=[('Humo', 'Humo'), ('UzCard', 'UzCard'), ('Click', 'Click'), ('Perevod', 'Perevod'), ('Others', 'Others')], max_length=150),
        ),
        migrations.AlterField(
            model_name='expense',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='status',
            field=models.CharField(choices=[('Comer', 'Comer'), ('Waiting', 'Waiting'), ('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('First Lesson', 'First Lesson'), ('Wrong Number', 'Wrong Number'), ('Deposit', 'Deposit'), ('Deleted', 'Deleted'), ('Frozen', 'Frozen')], max_length=20, null=True),
        ),
    ]
