# Generated by Django 5.1.1 on 2024-11-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_tenantuser_is_teacher_alter_tenantuser_role'),
        ('student', '0010_expense_category_expense_types_alter_expense_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.tenant'),
        ),
    ]
