# Generated by Django 5.1.1 on 2024-11-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_expense_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.IntegerField(max_length=100)),
            ],
        ),
    ]
