# Generated by Django 5.1.1 on 2024-11-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_chert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chert',
        ),
        migrations.AddField(
            model_name='attendance',
            name='unit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='status',
            field=models.CharField(choices=[('Comer', 'Comer'), ('Waiting', 'Waiting'), ('Active', 'Active'), ('Unpaid', 'Unpaid'), ('First Lesson', 'First Lesson'), ('Wrong Number', 'Wrong Number'), ('Deposit', 'Deposit'), ('Deleted', 'Deleted'), ('Frozen', 'Frozen'), ('Tekin', 'Tekin')], max_length=20, null=True),
        ),
    ]
