# Generated by Django 4.2 on 2024-09-04 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='birth_certificate_no',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='religion',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='source',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('Friend', 'Friend'), ('Facebook', 'Facebook')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Waiting', 'Waiting'), ('Negative', 'Negative')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=329439, unique=True),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(max_length=15)),
                ('date', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.personalinfo')),
            ],
        ),
    ]
