# Generated by Django 4.2 on 2024-09-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_remove_personalinfo_birth_certificate_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=820942, unique=True),
        ),
    ]
