# Generated by Django 5.1.1 on 2024-12-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Absent', 'Absent'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='status',
            field=models.CharField(choices=[('Comer', 'Comer'), ('Waiting', 'Waiting'), ('Active', 'Active'), ('Unpaid', 'Unpaid'), ('First Lesson', 'First Lesson'), ('Wrong Number', 'Wrong Number'), ('Deposit', 'Deposit'), ('Deleted', 'Deleted'), ('Frozen', 'Frozen'), ('Tekin', 'Tekin'), ('Duplicate', 'Duplicate')], max_length=20, null=True),
        ),
    ]
