# Generated by Django 5.1.1 on 2025-01-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_attendance_status_alter_personalinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='status',
            field=models.CharField(choices=[('Comer', 'Comer'), ('Waiting', 'Waiting'), ('Active', 'Active'), ('Unpaid', 'Unpaid'), ('First Lesson', 'First Lesson'), ('Wrong Number', 'Wrong Number'), ('Deposit', 'Deposit'), ('Deleted', 'Deleted'), ('Frozen', 'Frozen'), ('Free', 'Free'), ('Duplicate', 'Duplicate'), ('Another Branch', 'Another Branch')], max_length=20, null=True),
        ),
    ]
