# Generated by Django 4.2 on 2024-09-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0018_alter_academicinfo_registration_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='first_come_day',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='first_lesson_day',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='goal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.personalinfo'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=889384, unique=True),
        ),
    ]
