# Generated by Django 4.2 on 2024-09-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_personalinfo_first_come_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=474199, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_come_day',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_lesson_day',
            field=models.DateField(default=None, null=True),
        ),
    ]
