# Generated by Django 4.2 on 2024-09-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_alter_academicinfo_registration_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=349679, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_come_day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_lesson_day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
