# Generated by Django 4.2 on 2024-09-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=609602, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
