# Generated by Django 5.1.1 on 2024-09-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_alter_academicinfo_registration_no'),
        ('teacher', '0002_remove_personalinfo_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='level',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=919525, unique=True),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('EVEN', 'EVEN'), ('ODD', 'ODD')], max_length=100)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.personalinfo')),
            ],
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.group'),
        ),
    ]
