# Generated by Django 5.1.1 on 2024-09-09 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_remove_personalinfo_level_personalinfo_balance_and_more'),
        ('teacher', '0002_remove_personalinfo_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=986620, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='teacher.personalinfo'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student.group'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='status',
            field=models.CharField(choices=[('Comer', 'Comer'), ('Waiting', 'Waiting'), ('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('First Lesson', 'First Lesson'), ('Wrong Number', 'Wrong Number')], max_length=20, null=True),
        ),
    ]
