# Generated by Django 5.1.1 on 2024-09-09 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_remove_personalinfo_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=726165, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student.group'),
        ),
    ]
