# Generated by Django 5.1.1 on 2024-09-09 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_personalinfo_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='student',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=85941, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balances', to='student.billing'),
        ),
    ]
