# Generated by Django 5.1.1 on 2024-09-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_remove_billing_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=978183, unique=True),
        ),
    ]
