# Generated by Django 5.1.1 on 2024-09-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=9630, unique=True),
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
