# Generated by Django 5.1.1 on 2024-09-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_alter_academicinfo_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='last_deduction',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=869722, unique=True),
        ),
    ]
