# Generated by Django 5.1.1 on 2024-09-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='language',
            field=models.CharField(choices=[('Russian', 'Russian'), ('English', 'English'), ('French', 'French')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='learning_duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=559035, unique=True),
        ),
    ]
